  version: '3'
    
  services:
    postgres:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
    web:
      build: web/
      command: /app/start.sh
      volumes:
      - static_volume:/app/static
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - postgres
    nginx:
      build: nginx/
      volumes:
      - static_volume:/app/static
      ports:
        - "88:80"
      depends_on:
        - web
  volumes:
    postgres_data:
    static_volume: